### ISSUE TITLE
Bugs in Web Access Requests

### ISSUE THREAD

**Issue by swenghj** [attendanceproject/djattendance#491]
Bugs
- [x] E-shepherding is not available from trainee perspective
  - [x] verified 
- Web access request
  - trainee perspective
    - [x] calender is not popping up when creating request
        - [x] verified 
  - trainer perspective: 
    - [x] the web access create link should not be shown - remove it e9d494c
         - [x] verified 
    - [x] give direct Web Access via MAC address is not enabled 
         - [x] verified 
    - [x] direct Web Access causes a time out error  
         - [ ] verified 
  - [x] both trainee and trainer: icon images not available 
     - [ ] verified 
- [ ] MAC address is not shown on the first page
   - [ ] verified

**Comment by billyeh** [comment]
Oh yeah. I fixed a few of these in 0fbd0f6.

**Comment by billyeh** [comment]
54bb2e6 adds the link for giving direct web access. User must be in groups administration or networks to see it.

**Comment by billyeh** [comment]
Update on the MAC address: two solutions I can come up with:

* Mock the function call to return an address for testing (https://pypi.python.org/pypi/mock). It'd be nice if we could upgrade to Python3 where it's part of the standard `unittest` library, but it should be fine either way
* Modify the function to just return the server's MAC address instead of `None` using code like this: https://stackoverflow.com/questions/159137/getting-mac-address (works on my computer)

**Comment by swenghj** [comment]
> trainer perspective: 
>>  [x] the web access create link should not be shown - remove it 

still shows create web access link from TA account. I think it should not be there

> 54bb2e6 adds the link for giving direct web access. User must be in groups administration or networks to see it. 

I get time out error when creating it. 

    Request Method: 	POST
    Request URL: 	http://localhost:8000/web_access/direct-web-access
    Django Version: 	1.8.1
    Exception Type: 	timeout
    Exception Value: 	timed out
    Exception Location: 	/usr/lib/python2.7/socket.py in meth, line 224
    Python Executable: 	/home/hyunjoon/.virtualenvs/dev/bin/python
    Python Version: 	2.7.6

> Update on the MAC address: two solutions I can come up with:

I saw the live server does not have this issue. but I was wondering why it does not work in local computer. I think that 2nd option probably would be okay for a quick fix. So it is not possible to return the local MAC address? Actually, e-shepherding submission causes an error due to the MAC address not available in a local environment.

**Comment by billyeh** [comment]
Oops, forgot about the create new request link. 

Anything that relies on getting the MAC won't work locally because of the command it uses. (`arp -n`).
